#!/bin/sh

# launches PEmicro's GDB server automatically with correct parameters:
# detect where the cyclone is attached to and start PEmicro's gdbserver there
#
# This script assumes you have the pegdbserver executable on PATH

serverport=7244

pemicrotty="$(pegdbserver -showhardware | tr -s ' ' '\n' | grep -- -PORT | head -n 1 | cut -d = -f 2)"

if [ -z "$pemicrotty" ]; then
    echo ERROR: no PE micro interface found! 1>&2
    exit 1
fi

# use pegdbserver -devicelist to list all devices you can pass
# to -device

exec pegdbserver \
    -device=NXP_S32K1xx_S32K148F2M0M11 \
    -startserver \
    -serverport=7244 \
    -interface=USBMULTILINK \
    -speed=5000 \
    "-port=$pemicrotty" \
    -st
